name: Build (Windows)

on:
  push:
    branches: [ main ]
    paths:
      - '**.h'
      - '**.cpp'
      - '**.json'
      - '**.bat'
      - 'CMakeLists.txt'
      - 'src/**'
      - 'resources/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.h'
      - '**.cpp'
      - '**.json'
      - '**.bat'
      - 'CMakeLists.txt'
      - 'src/**'
      - 'resources/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'b02e341c927f16d991edbd915d8ea43eac52096c'
      
    - name: Build with CMake
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 17 2022" -A x64
        cmake --build build --config Debug --verbose
        
    - name: Check build artifacts
      run: |
        echo "Checking build output..."
        if (Test-Path "build\Debug\bt-lumina.exe") {
          echo "✅ Main executable found"
          Get-ChildItem "build\Debug\bt-lumina.exe" | Select-Object Name, Length
        } else {
          echo "❌ Main executable not found"
        }
        
    - name: Verify build success
      run: |
        if (Test-Path "build\Debug\bt-lumina.exe") {
          echo "✅ Build successful - executable exists"
          exit 0
        } else {
          echo "❌ Build failed - executable not found"
          exit 1
        } 