# Windows CI
name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.10
      with:
        cmake-version: '3.21.1'
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
    - name: Install vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: ctest --test-dir build --output-on-failure 