# Windows CI
name: Windows

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.10
      with:
        cmake-version: '3.21.1'
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
    - name: Install vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: '0cf34c184ce990471435b5b9c92edcf7424930b1'
    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" -DCMAKE_SYSTEM_VERSION="10.0" -DCMAKE_CXX_STANDARD=20
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: ctest --test-dir build --output-on-failure 